// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using NBA.Models;
//
//    var teamsConfig = TeamsConfig.FromJson(jsonString);

namespace NBA.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class TeamsConfig
    {
        [JsonProperty("teams")]
        public Teams Teams { get; set; }
    }

    public partial class Teams
    {
        [JsonProperty("config")]
        public List<Config> Config { get; set; }
    }

    public partial class Config
    {
        [JsonProperty("teamId")]
        public string TeamId { get; set; }

        [JsonProperty("tricode")]
        public string Tricode { get; set; }

        [JsonProperty("primaryColor")]
        public string PrimaryColor { get; set; }

        [JsonProperty("secondaryColor", NullValueHandling = NullValueHandling.Ignore)]
        public string SecondaryColor { get; set; }

        [JsonProperty("app", NullValueHandling = NullValueHandling.Ignore)]
        public App App { get; set; }

        [JsonProperty("web", NullValueHandling = NullValueHandling.Ignore)]
        public Web Web { get; set; }

        [JsonProperty("ttsName", NullValueHandling = NullValueHandling.Ignore)]
        public string TtsName { get; set; }
    }

    public partial class App
    {
        [JsonProperty("android")]
        public string Android { get; set; }

        [JsonProperty("androidDeepLink")]
        public string AndroidDeepLink { get; set; }

        [JsonProperty("ios")]
        public string Ios { get; set; }

        [JsonProperty("iosDeepLink")]
        public string IosDeepLink { get; set; }

        [JsonProperty("tickets")]
        public string Tickets { get; set; }
    }

    public partial class Web
    {
        [JsonProperty("homepage")]
        public string Homepage { get; set; }

        [JsonProperty("tickets")]
        public string Tickets { get; set; }
    }

    public partial class TeamsConfig
    {
        public static TeamsConfig FromJson(string json) => JsonConvert.DeserializeObject<TeamsConfig>(json, NBA.Models.Converter.Settings);
    }

}
